>P1;P22/1-146
structureX: 2anx: 1:A: 146:A:  P22:: 1.04:
---MMQISSNGITRLKREEGERLKAY---SDSRGI--PTIGVGHTGKVDGNS-VASGMT-------------
--ITAEKSSELLKE-DLQWVEDAISSLVRVPLNQNQYDAMCSLIFNIGKSAFAGSTVLRQLNLKNYQAAADA
FLLWKKA---------GKDPDILLP------RR-------RRERALFLS-*

>P1;SpmX
structureX: spmx: 4:A: 147:A: SpmX:: :
----HKISRAGVELIKSFEGLRQQAS---QLPDGR--WMIGYGHT-----FS-AREGAR-------------
--VTAEDADALLRF-DLLPIVEAVNNLVHTPLTQNQFDALVSFCFNIGIEAFGQSDVLRRVNEGRVTEAAQA
MDNWTSAEFNGQ----TYVLAPLIR------RR-------ASEKSLFL--*

>P1;SpmX-Pb
sequence:::::::::
EFSTMKTGQTGLNLIKAYEGLRLTAQAEPALPDGERLWSVGYGHR-----KT-AAQGMT-------------
--VTEKEAARLLAD-DIGPIEGLIQSTVRCPLNQNEHDALVSLIFNIGEENFRRSTVLAKLNDGDKLAAADA
IERWSRARVDGR----LVKLDGLVR------RR-------AAEKSLFLMP*

>P1;SpmXL-Pb
sequence:::::::::
----MHISGEGIELIKAFEGLRLDVY---DDGVGI--WTIGYGHT-----GAIEVDGKRYSSVAAAYDDLGP
FSISEAYAEDLLRE-DLQVFVAGVDRALKVTPTQSMFDALVSLAFNIGVSAFSKSTAVKRHNKRDFEGAAEA
ITWWNKA--GGQ------VLTGLVR------RR-------SAEAALYLRD*

>P1;SpmXL-Po
sequence:::::::::
---MQRTSDIGIALIKRFEGLRLKAY---RDVAGV--WTIGYGHT-----GGQARAGAE-------------
--ITASEAEALLAR-DLGRFEEAVRRLVG-RLPQQQFDALVSLSYNIGIGAFARSTALARLKAGDGRGAAEA
IGWWNKATIGGE----KRVLPGLVR------RR-------AAEAALFLEA*
